name: object-locator
channels:
  - pytorch
  - conda-forge
dependencies:
  - imageio=2.3.0
  - ipdb=0.11
  - ipython=6.3.1
  - ipython_genutils=0.2.0
  - matplotlib=3.3.2
  - numpy=1.15.4
  - opencv=3.4.2
  - pandas=0.22.0
  - parse=1.8.2
  - pip=21.3.1
  - python=3.6.11
  - scikit-image=0.13.1
  - scikit-learn=0.23.1
  - scipy=1.5.1
  - setuptools=39.1.0
  - tqdm=4.23.1
  - xmltodict=0.11.0
  - pytorch=1.1.0
  - python-dateutil=2.8.2
  - pip:
      - ballpark==1.4.0
      - visdom==0.1.8.5
      - peterpy
      - torchvision==0.2.1
