name: object-locator
channels:
  - conda-forge
dependencies:
  - imageio=2.3.0
  - ipdb=0.11
  - ipython=6.3.1
  - ipython_genutils=0.2.0
  - matplotlib=2.2
  - numpy=1.15.4
  - opencv=3.4.1
  - pandas=0.22.0
  - parse=1.8.2
  - pip
  - python=3.6.5
  - scikit-image=0.13.1
  - scikit-learn=0.19.1
  - scipy=1.0.1
  - setuptools=39.1.0
  - tqdm=4.23.1
  - xmltodict=0.11.0
  - pytorch=1.0.0
  - python-dateutil
  - ca-certificates
  - certifi
  - openssl
